# numpy

\- открытая библиотка для научных исследований. Дает возможность манипулирования различными массивами.


### ndarray

\- n-размерный массив. В данном случае одномерный пока рассматривается.

Выполнять *мат. операции и операции сравнения*, которая будет применена к каждой единице выборки. (Вместо map). 
Изменит текущий объект array.

*Поддерживает*: max, min, sorted, list, len

Каждый ndarray имеет свой dtype.

Значения изменить можно. А размерность после создания нет.

In [1]:
import numpy as np
import pandas as pd

# func array(obj, dtype)
vector = np.array([1, 2, 4, 1000, 203, 33])

type(vector)

numpy.ndarray

In [2]:
# index
vector[::-1], vector[-1]

(array([  33,  203, 1000,    4,    2,    1]), 33)

In [3]:
# assign
vector[0] = 999999
vector

array([999999,      2,      4,   1000,    203,     33])

In [4]:
max(vector), len(vector), vector ** 2

(999999,
 6,
 array([999998000001,            4,           16,      1000000,
               41209,         1089]))

### matrix

\- многомерные данные. Тот же array но сложнее.

In [10]:
source = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

matrix = np.array(source)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# каждая единица совокупности меняется
matrix * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

m flatten makes rows as one dimention


In [7]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arrt shape returns a tuple of size (rows, vars)
attr size кол-во столбцов
attr ndim кол-во строк


In [16]:
source.append([10, 11, 12])
matrix = np.array(source)
matrix.shape, matrix.ndim, matrix.size

((9, 3), 2, 27)

In [9]:
# syntax среза: row_index, срез. Вернет новый array, либо единицу совокупности.
matrix, matrix[1, :], matrix[2, :1]

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([4, 5, 6]),
 array([7]))

In [10]:
# Индексация по признаку
# если первый вернул матрицу, второй вернет по столбцам.
matrix[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [11]:
# attr base позволяет получить исх. матрицу
new_matrix = matrix[:, -1]
new_matrix, new_matrix.base

(array([ 3,  6,  9, 12]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

#### operations

In [12]:
array1 = np.array([[1, 2], [3, 4]], dtype=np.float64)
array2 = np.array([[5, 6], [7, 8]], dtype=np.float64)
# addition
m_sum1 = array1 + array2
m_sum2 = np.add(array1, array2)

# сравнение матриц происходит между единицами.
m_sum1 == m_sum2

array([[ True,  True],
       [ True,  True]])

In [13]:
# поэлементарное вычитание
s1, s2 = array1 - array2, np.subtract(array1, array2)

s1, s2

(array([[-4., -4.],
        [-4., -4.]]),
 array([[-4., -4.],
        [-4., -4.]]))

In [17]:
# multiply
s1, s2 = array1 * array2, np.multiply(array1, array2)
s1 == s2

array([[ True,  True],
       [ True,  True]])

f arange т.е. array range

In [4]:
np.arange(10, step=2)

array([0, 2, 4, 6, 8])

m reshape((rows, cols)) делит одномерный на многомерный массив.

In [4]:
a = np.arange(10)
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

f union1d вернет array с общими значениями оп одному разу.
f concatenate аналогично, но не сортирует

In [7]:
a = pd.Series([1, 2, 3, 4])
b = pd.Series([3, 4, 5, 6, 3])
w = pd.Series(np.union1d(a, b))
w

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

f np.intersect1d вернет array с пересекающимися знаениями

In [8]:
l = pd.Series(np.intersect1d(a, b))
l

0    3
1    4
dtype: int64

f linespace(start, stop, amount) - вернет array чисел, от start до stop с кол-вом чисел amount, между которыми одинаковый интервал.

In [4]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])