# numpy

\- открытая библиотка для научных исследований. Дает возможность манипулирования различными массивами.


### ndarray

\- n-размерный массив. В данном случае одномерный пока рассматривается.

Выполнять *мат. операции и операции сравнения*, которая будет применена к каждой единице выборки. (Вместо map). 
Изменит текущий объект array.

*Поддерживает*: max, min, sorted, list, len

Каждый ndarray имеет свой dtype.

Значения изменить можно. А размерность после создания нет.

In [21]:
import numpy as np
import pandas as pd

# func array(obj, dtype)
vector = np.array([1, 2, 4, 1000, 203, 33])

type(vector)

numpy.ndarray

In [2]:
# index
vector[::-1], vector[-1]

(array([  33,  203, 1000,    4,    2,    1]), 33)

In [3]:
# assign
vector[0] = 999999
vector

array([999999,      2,      4,   1000,    203,     33])

In [4]:
max(vector), len(vector), vector ** 2

(999999,
 6,
 array([999998000001,            4,           16,      1000000,
               41209,         1089]))

### matrix

\- многомерные данные. Тот же array но сложнее.

In [10]:
source = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

matrix = np.array(source)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# каждая единица совокупности меняется
matrix * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

m flatten makes rows as one dimention


In [7]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arrt shape returns a tuple of size (rows, vars)
attr size кол-во столбцов
attr ndim кол-во строк


In [16]:
source.append([10, 11, 12])
matrix = np.array(source)
matrix.shape, matrix.ndim, matrix.size

((9, 3), 2, 27)

In [9]:
# syntax среза: row_index, срез. Вернет новый array, либо единицу совокупности.
matrix, matrix[1, :], matrix[2, :1]

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([4, 5, 6]),
 array([7]))

In [10]:
# Индексация по признаку
# если первый вернул матрицу, второй вернет по столбцам.
matrix[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [11]:
# attr base позволяет получить исх. матрицу
new_matrix = matrix[:, -1]
new_matrix, new_matrix.base

(array([ 3,  6,  9, 12]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

#### operations

In [12]:
array1 = np.array([[1, 2], [3, 4]], dtype=np.float64)
array2 = np.array([[5, 6], [7, 8]], dtype=np.float64)
# addition
m_sum1 = array1 + array2
m_sum2 = np.add(array1, array2)

# сравнение матриц происходит между единицами.
m_sum1 == m_sum2

array([[ True,  True],
       [ True,  True]])

In [13]:
# поэлементарное вычитание
s1, s2 = array1 - array2, np.subtract(array1, array2)

s1, s2

(array([[-4., -4.],
        [-4., -4.]]),
 array([[-4., -4.],
        [-4., -4.]]))

In [17]:
# multiply
s1, s2 = array1 * array2, np.multiply(array1, array2)
s1 == s2

array([[ True,  True],
       [ True,  True]])

f arange т.е. array range

In [4]:
np.arange(10, step=2)

array([0, 2, 4, 6, 8])

m reshape((rows, cols)) делит одномерный на многомерный массив.

In [4]:
a = np.arange(10)
a.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

f union1d вернет array с общими значениями оп одному разу.
f concatenate аналогично, но не сортирует

In [7]:
a = pd.Series([1, 2, 3, 4])
b = pd.Series([3, 4, 5, 6, 3])
w = pd.Series(np.union1d(a, b))
w

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

f np.intersect1d вернет array с пересекающимися знаениями

In [8]:
l = pd.Series(np.intersect1d(a, b))
l

0    3
1    4
dtype: int64

f linespace(start, stop, amount) - вернет array чисел, от start до stop с кол-вом чисел amount, между которыми одинаковый интервал.

In [4]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### random module

In [4]:
# rand(n, m) - random decimal values (<1), n-rows and m-cols.
np.random.rand(3, 5)

array([[0.39644194, 0.22084716, 0.34059099, 0.71674046, 0.32091371],
       [0.22049875, 0.31969473, 0.90630989, 0.44192773, 0.88898049],
       [0.36279004, 0.67757648, 0.4267943 , 0.94496051, 0.84399969]])

In [ ]:
# randint - random imteger from low to high
np.random.randint(1, 10)

In [7]:
# random_sample
np.random.random_sample(10)

array([0.92595413, 0.55393597, 0.23086826, 0.47942633, 0.63716663,
       0.06079934, 0.75160233, 0.6893118 , 0.90545859, 0.86733877])

In [20]:
# random numbers from low to high
np.random.randn(10)

array([-0.81798887, -0.92337735,  1.56544189,  1.01053747,  0.65759917,
        0.24912741, -0.04236247,  0.36528244, -0.34704886,  1.09608025])

In [26]:
# random data for normal distibution normal(mean-center, std, len of data)
np.random.normal(0, 1, 100)

array([ 1.79785683, -1.76418243, -0.80054348, -1.45176872, -1.17710498,
        0.98494893,  1.41371173, -2.39873883,  0.27421767,  0.44023701,
        0.63342775,  0.50897746,  0.21536471, -0.00903414,  1.30342343,
        0.23228767,  0.61457397,  0.16456004, -0.32263014,  0.34309738,
       -0.86108342,  0.622687  , -1.31656178,  0.25202594, -0.34015092,
        0.60614778,  1.52002609, -0.41548814,  1.01168106,  1.66742926,
        0.42625471,  0.0414708 , -0.21808325, -0.75304798, -0.62007133,
       -0.70261709,  0.5844689 ,  2.62195187,  0.30223728, -1.1380207 ,
        1.02782531, -0.36607731, -1.50503552,  1.76692042, -0.77019789,
       -0.3433448 ,  0.73215463, -2.27792261,  0.22534981,  0.24488333,
        0.04436734, -1.50484332,  0.55955569,  0.16543161,  0.97273209,
        0.73317929,  0.92730129, -0.92227463, -0.50216   ,  1.09212269,
        2.08182528,  0.85830823,  0.19056015, -1.17657852,  0.19878596,
       -1.54011742,  1.669123  ,  1.35102652, -0.65368009, -0.87